```
name: Self Hosted Runner Test # Workflow name

on:
  push:

jobs:
  ci: # CI Stage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Repository
        run: |
          echo "Running CI..."
          ls -la
          cat index.txt

  deploy: # CD Stage
    needs: ci
    runs-on: habib-runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show System Information
        run: |
          echo "Runner is working!"
          hostname
          whoami
          pwd
          uname -a

      - name: List Files
        run: ls -la

      - name: Display File Content
        run: cat index.txt
```
